package com.goldwarehouse.mapper;

import com.goldwarehouse.entity.Account;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbg.generated Tue Oct 23 15:09:25 CST 2018
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounts
     *
     * @mbg.generated Tue Oct 23 15:09:25 CST 2018
     */
    int insertSelective(Account record);
}